[package]
name = "gugle"
version = "0.1.0"
edition = "2024"

[dependencies]
gurt = "0.1.0"
serde_json = "1.0.143"
serde = { version = "1.0", features = ["derive"] }
sqlite = "0.37.0"
tokio = "1.47.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
